const KEY='patrick-budget-pwa-v1';
const today=()=>new Date().toISOString().slice(0,10), monthKey=d=>d.slice(0,7), currentMonth=()=>today().slice(0,7);
const uid=()=>crypto.randomUUID();
const defaults={income:0,payFrequency:'biweekly',setupComplete:false,accounts:{checking:0,emergency:0,brokerage:0},bills:[{id:uid(),name:'Mortgage',amount:0,dueDay:1},{id:uid(),name:'Internet',amount:0,dueDay:1},{id:uid(),name:'Electric',amount:0,dueDay:1},{id:uid(),name:'Water',amount:0,dueDay:1}],categories:[{id:uid(),name:'Groceries',budget:0},{id:uid(),name:'Restaurants',budget:0},{id:uid(),name:'Gas / Transportation',budget:0},{id:uid(),name:'Shopping',budget:0},{id:uid(),name:'Entertainment',budget:0},{id:uid(),name:'Home / Misc.',budget:0}],goals:[{id:uid(),name:'Hawaii 2027',saved:0,target:0,monthly:0,targetDate:'2027-06-01'}],transactions:[],billStatus:{}};
let s=load(),historyMonth=currentMonth();
function load(){try{let x=Object.assign(structuredClone(defaults),JSON.parse(localStorage.getItem(KEY)||'{}'));x.accounts=Object.assign({},defaults.accounts,x.accounts||{});x.bills=(x.bills||[]).map(b=>({...b,dueDay:b.dueDay||1}));x.payFrequency=x.payFrequency||'monthly';return x}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(s));render()}
const $=q=>document.querySelector(q), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0), esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function monthlyIncome(){let n=Number(s.income)||0;return s.payFrequency==='biweekly'?n*26/12:s.payFrequency==='semimonthly'?n*2:n}
function txForMonth(m){return s.transactions.filter(t=>monthKey(t.date)===m)} function monthTx(){return txForMonth(currentMonth())} function catSpent(id,m=currentMonth()){return txForMonth(m).filter(t=>t.categoryId===id).reduce((a,t)=>a+t.amount,0)} function paid(id){return !!(s.billStatus[currentMonth()]||{})[id]} function setPaid(id,v){s.billStatus[currentMonth()]??={};s.billStatus[currentMonth()][id]=v;save()}
function monthsUntil(date){if(!date)return 0;let now=new Date(),end=new Date(date+'T12:00:00');return Math.max(1,(end.getFullYear()-now.getFullYear())*12+end.getMonth()-now.getMonth())}
function requiredMonthly(g){let rem=Math.max(0,(g.target||0)-(g.saved||0));return g.targetDate&&rem?rem/monthsUntil(g.targetDate):0}
function render(){const d=new Date();$('#monthLabel').textContent=d.toLocaleDateString(undefined,{month:'long',year:'numeric'});let billTotal=s.bills.reduce((a,b)=>a+b.amount,0),rem=s.bills.filter(b=>!paid(b.id)).reduce((a,b)=>a+b.amount,0),spent=monthTx().reduce((a,t)=>a+t.amount,0),flex=s.categories.reduce((a,c)=>a+c.budget,0),goals=s.goals.reduce((a,g)=>a+g.monthly,0),safe=monthlyIncome()-billTotal-flex-goals;$('#safe').textContent=money(safe);let days=Math.max(1,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()-d.getDate()+1);$('#safeWeek').textContent=`${money(Math.max(0,safe-spent)/(days/7))}/week left`;$('#remainingBills').textContent=money(rem);$('#remainingCount').textContent=`${s.bills.filter(b=>!paid(b.id)).length} unpaid`;$('#spent').textContent=money(spent);$('#budgetStatus').textContent=`${money(Math.max(0,flex-spent))} flexible budget left`;$('#goalMonthly').textContent=money(goals);
let upcoming=[...s.bills].filter(b=>!paid(b.id)).sort((a,b)=>a.dueDay-b.dueDay).slice(0,3);$('#homeBills').innerHTML=upcoming.length?upcoming.map(b=>`<div class="row"><div class="grow"><div class="name">${esc(b.name)}</div><div class="small">${money(b.amount)} · due day ${b.dueDay}</div></div><button data-paid="${b.id}">Paid</button></div>`).join(''):'<div class="empty">All recurring bills are marked paid.</div>';
$('#homeGoals').innerHTML=s.goals.length?s.goals.map(g=>{let pct=g.target?Math.min(100,g.saved/g.target*100):0,req=requiredMonthly(g),on=g.targetDate&&g.target?g.monthly>=req:false;return `<div class="row"><div class="grow"><div class="progressline"><b>${esc(g.name)}</b><span>${money(g.saved)} / ${g.target?money(g.target):'No target'}</span></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div class="small">${g.targetDate&&g.target?`${money(req)}/mo needed · <span class="${on?'good':'warn'}">${on?'On track':'Needs '+money(Math.max(0,req-g.monthly))+'/mo more'}</span>`:money(g.monthly)+'/mo planned'}</div></div></div>`}).join(''):'<div class="empty">Add a goal to start forecasting.</div>';
$('#historyMonth').value=historyMonth;let hist=txForMonth(historyMonth);$('#transactionList').innerHTML=hist.length?[...hist].sort((a,b)=>b.date.localeCompare(a.date)).map(t=>{let c=s.categories.find(c=>c.id===t.categoryId);return `<div class="row"><div class="grow"><div class="name">${esc(t.note||c?.name||'Expense')}</div><div class="small">${esc(c?.name||'Other')} · ${t.date}</div></div><b>${money(t.amount)}</b><button class="danger" data-del-tx="${t.id}">Delete</button></div>`}).join(''):'<div class="empty">No expenses logged for this month.</div>';
$('#billEditor').innerHTML=s.bills.map(b=>`<div class="row"><div class="grow"><div class="name">${esc(b.name)}</div><div class="small">${money(b.amount)} · due day ${b.dueDay}</div></div><button data-edit-bill="${b.id}">Edit</button><button class="danger" data-del-bill="${b.id}">Delete</button></div>`).join('');
$('#categoryEditor').innerHTML=s.categories.map(c=>{let x=catSpent(c.id),p=c.budget?Math.min(100,x/c.budget*100):0;return `<div class="row"><div class="grow"><div class="progressline"><b>${esc(c.name)}</b><span>${money(x)} / ${money(c.budget)}</span></div><div class="bar"><div class="fill" style="width:${p}%"></div></div></div><button data-edit-cat="${c.id}">Edit</button><button class="danger" data-del-cat="${c.id}">Delete</button></div>`}).join('');
$('#goalEditor').innerHTML=s.goals.map(g=>{let req=requiredMonthly(g);return `<div class="row"><div class="grow"><div class="name">${esc(g.name)}</div><div class="small">${money(g.saved)} saved · ${money(g.monthly)}/mo${g.targetDate?' · '+g.targetDate:''}${req?' · '+money(req)+'/mo needed':''}</div></div><button data-edit-goal="${g.id}">Edit</button><button class="danger" data-del-goal="${g.id}">Delete</button></div>`}).join('');
$('#income').value=s.income;$('#payFrequency').value=s.payFrequency;['checking','emergency','brokerage'].forEach(k=>$('#'+k).value=s.accounts[k]);$('#expCategory').innerHTML=s.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');bindDynamic()}
function bindDynamic(){document.querySelectorAll('[data-paid]').forEach(x=>x.onclick=()=>setPaid(x.dataset.paid,true));document.querySelectorAll('[data-del-tx]').forEach(x=>x.onclick=()=>{s.transactions=s.transactions.filter(t=>t.id!==x.dataset.delTx);save()});document.querySelectorAll('[data-edit-bill]').forEach(x=>x.onclick=()=>openItem('bill',x.dataset.editBill));document.querySelectorAll('[data-del-bill]').forEach(x=>x.onclick=()=>{s.bills=s.bills.filter(b=>b.id!==x.dataset.delBill);save()});document.querySelectorAll('[data-edit-cat]').forEach(x=>x.onclick=()=>openItem('cat',x.dataset.editCat));document.querySelectorAll('[data-del-cat]').forEach(x=>x.onclick=()=>{s.categories=s.categories.filter(c=>c.id!==x.dataset.delCat);save()});document.querySelectorAll('[data-edit-goal]').forEach(x=>x.onclick=()=>openItem('goal',x.dataset.editGoal));document.querySelectorAll('[data-del-goal]').forEach(x=>x.onclick=()=>{s.goals=s.goals.filter(g=>g.id!==x.dataset.delGoal);save()})}
function openExpense(){$('#expAmount').value='';$('#expNote').value='';$('#expDate').value=today();$('#expenseDialog').showModal()} $('#expenseForm').onsubmit=e=>{e.preventDefault();let a=Number($('#expAmount').value);if(!(a>0))return;s.transactions.push({id:uid(),amount:a,categoryId:$('#expCategory').value,note:$('#expNote').value.trim(),date:$('#expDate').value});$('#expenseDialog').close();save()};
let itemCtx=null;function openItem(type,id=null){itemCtx={type,id};let arr=type==='bill'?s.bills:type==='cat'?s.categories:s.goals,obj=id?arr.find(x=>x.id===id):null;$('#itemTitle').textContent=(id?'Edit ':'Add ')+(type==='bill'?'bill':type==='cat'?'category':'goal');if(type==='bill')$('#itemFields').innerHTML=`<div><div class="label">Name</div><input name="name" required value="${esc(obj?.name||'')}"></div><div class="form two"><div><div class="label">Monthly amount</div><input name="amount" type="number" min="0" step=".01" required value="${obj?.amount||0}"></div><div><div class="label">Due day</div><input name="dueDay" type="number" min="1" max="31" required value="${obj?.dueDay||1}"></div></div>`;if(type==='cat')$('#itemFields').innerHTML=`<div><div class="label">Name</div><input name="name" required value="${esc(obj?.name||'')}"></div><div><div class="label">Monthly budget</div><input name="budget" type="number" min="0" step=".01" required value="${obj?.budget||0}"></div>`;if(type==='goal')$('#itemFields').innerHTML=`<div><div class="label">Goal name</div><input name="name" required value="${esc(obj?.name||'')}"></div><div class="form two"><div><div class="label">Saved</div><input name="saved" type="number" min="0" step=".01" value="${obj?.saved||0}"></div><div><div class="label">Target</div><input name="target" type="number" min="0" step=".01" value="${obj?.target||0}"></div><div><div class="label">Monthly contribution</div><input name="monthly" type="number" min="0" step=".01" value="${obj?.monthly||0}"></div><div><div class="label">Target date</div><input name="targetDate" type="date" value="${obj?.targetDate||''}"></div></div>`;$('#itemDialog').showModal()}
$('#itemForm').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),{type,id}=itemCtx,arr=type==='bill'?s.bills:type==='cat'?s.categories:s.goals,obj=id?arr.find(x=>x.id===id):{id:uid()};obj.name=fd.get('name').trim();if(type==='bill'){obj.amount=Number(fd.get('amount'))||0;obj.dueDay=Math.min(31,Math.max(1,Number(fd.get('dueDay'))||1))}if(type==='cat')obj.budget=Number(fd.get('budget'))||0;if(type==='goal'){obj.saved=Number(fd.get('saved'))||0;obj.target=Number(fd.get('target'))||0;obj.monthly=Number(fd.get('monthly'))||0;obj.targetDate=fd.get('targetDate')||''}if(!id)arr.push(obj);$('#itemDialog').close();save()};
function exportData(){let blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`budget-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)} $('#exportBtn').onclick=exportData;$('#backupTop').onclick=exportData;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let j=JSON.parse(await f.text());if(!j||!Array.isArray(j.transactions))throw 0;s=j;save();alert('Backup imported.')}catch{alert('That file is not a valid budget backup.')}e.target.value=''};
$('#income').onchange=e=>{s.income=Math.max(0,Number(e.target.value)||0);save()};$('#payFrequency').onchange=e=>{s.payFrequency=e.target.value;save()};['checking','emergency','brokerage'].forEach(k=>$('#'+k).onchange=e=>{s.accounts[k]=Math.max(0,Number(e.target.value)||0);save()});$('#historyMonth').onchange=e=>{historyMonth=e.target.value||currentMonth();render()};$('#quickAdd').onclick=$('#addTransaction').onclick=openExpense;$('#addBill').onclick=()=>openItem('bill');$('#addCategory').onclick=()=>openItem('cat');$('#addGoal').onclick=()=>openItem('goal');$('#viewBills').onclick=()=>{$('[data-page="budget"]').click()};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('dialog').close());document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.page).classList.add('active-page');b.classList.add('active');scrollTo(0,0)});
$('#setupForm').onsubmit=e=>{e.preventDefault();s.income=Math.max(0,Number($('#setupIncome').value)||0);s.payFrequency=$('#setupFrequency').value;s.accounts.checking=Math.max(0,Number($('#setupChecking').value)||0);s.setupComplete=true;$('#setupDialog').close();save()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();if(!s.setupComplete&&s.income===0)setTimeout(()=>$('#setupDialog').showModal(),150);
